

development:
  adapter: postgresql
  encoding: unicode
  database: split_development
  pool: 5
  host: localhost
  username: <%= Rails.application.credentials.dig(:postgresql,:username)%>
  password: <%= Rails.application.credentials.dig(:postgresql,:password)%>

test:
  adapter: postgresql
  encoding: unicode
  database: split_test
  pool: 5
  host: localhost
  username: <%= Rails.application.credentials.dig(:postgresql,:username)%>
  password: <%= Rails.application.credentials.dig(:postgresql,:password)%>

