

development:
  adapter: postgresql
  encoding: unicode
  database: split_development
  pool: 5
  host: localhost
  username: <%= Rails.application.credentials.dig(:postgresql,:username)%>
  password: <%= Rails.application.credentials.dig(:postgresql,:password)%>

test:
  adapter: postgresql
  encoding: unicode
  database: split_test
  pool: 5
  host: localhost
  username: <%= Rails.application.credentials.dig(:postgresql,:username)%>
  password: <%= Rails.application.credentials.dig(:postgresql,:password)%>

production:
  adapter: postgresql
  encoding: unicode
  username: <%= Rails.application.credentials.dig(:postgresql,:username)%>
  password: <%= Rails.application.credentials.dig(:postgresql,:password)%>
  host: <%= Rails.application.credentials.dig(:postgresql,:host)%>
  port: <%= Rails.application.credentials.dig(:postgresql,:port)%>
  database: <%= Rails.application.credentials.dig(:postgresql,:database)%>
  sslmode: <%= Rails.application.credentials.dig(:postgresql,:sslmode)%>
  sslrootcert: <%= Rails.application.credentials.dig(:postgresql,:sslrootcert)%>